### PR TITLE
(attempt to) Fix s3 upload

### PR DESCRIPTION
**Pull request by alexduf**
I'm not sure how to go about testing that @AWare , any suggestion?

### CODE REVIEW

**Comment by AWare** [comment]
Yeah, use `yarn link` to run locally and then you can use the dry run flag to see what would be uploaded.

**Review by AWare — COMMENTED** [review]
looks good though

**Review by AWare — APPROVED** [review]

**Comment by alexduf** [comment]
Thanks, I tested it works 👍

**Comment by AWare** [comment]
released as 0.1.7

**Pull request merged**
